### ISSUE TITLE
Catch is not  function

### ISSUE THREAD

**Issue by ivanturbinca** [yeoman/yeoman-test#106]
When I try to run my tests. I get this error:

```
Uncaught TypeError: this.generator.run(...).catch is not a function
      at RunContext._run (node_modules/yeoman-test/lib/run-context.js:171:29)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

```

**Comment by ivanturbinca** [comment]
Actually I used the package.json from [https://yeoman.io/authoring/index.html](url) which uses version 1.0.0 of yeoman-generator. I updated to version 4.10.1 and everything is ok
