### ISSUE TITLE
Issue migrating my generators' tests to TypeScript (ERR_PACKAGE_PATH_NOT_EXPORTED)

### ISSUE THREAD

**Issue by groovytron** [yeoman/yeoman-test#164]
Hi,

I'm having troubles migrating my generators' tests to TypeScript.

My project is https://github.com/groovytron/generator-skjol. The migration branch is `migrate-to-typescript`.

I get the following error when I run `npm run test` (which runs the tests with Mocha like the previous version of my project):

```
> generator-skjol@2.0.0 test
> nyc --all --reporter lcov mocha


Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/julien/Documents/swissted/generator-skjol/node_modules/yeoman-test/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:266:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:546:13)
    at resolveExports (node:internal/modules/cjs/loader:551:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:620:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/julien/Documents/swissted/generator-skjol/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/home/julien/Documents/swissted/generator-skjol/test/slides.spec.ts:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module.replacementCompile (/home/julien/Documents/swissted/generator-skjol/node_modules/append-transform/index.js:60:13)
    at Module.m._compile (/home/julien/Documents/swissted/generator-skjol/node_modules/ts-node/src/index.ts:1618:23)
    at module.exports (/home/julien/Documents/swissted/generator-skjol/node_modules/default-require-extensions/js.js:7:9)
    at /home/julien/Documents/swissted/generator-skjol/node_modules/append-transform/index.js:64:4
    at require.extensions.<computed> (/home/julien/Documents/swissted/generator-skjol/node_modules/ts-node/src/index.ts:1621:12)
    at Object.<anonymous> (/home/julien/Documents/swissted/generator-skjol/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.exports.requireOrImport (/home/julien/Documents/swissted/generator-skjol/node_modules/mocha/lib/nodejs/esm-utils.js:53:16)
    at async Object.exports.loadFilesAsync (/home/julien/Documents/swissted/generator-skjol/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/home/julien/Documents/swissted/generator-skjol/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/julien/Documents/swissted/generator-skjol/node_modules/mocha/lib/cli/run.js:370:5)
```

My current node version is `v19.4.0`.

Is there an issue with `yeoman-test`'s exports or am I doing something wrong with my Mocha TypeScript configuration ?

I tried to use Jest instead because I was suspecting there was an issue with `ts-node` when used with Mocha but I stumble on the same error. Jest is installed to. You can test with Jest by renaming the `slides.spec.jest.ts` into `slides.spec.ts` and run `npm run jest`.

I'm actually just testing the slides generator so only the script `slides.spec.ts` is executed at the moment. I will migrate the other tests once this one works.

Thanks a lot for your help and have a nice day.

**Comment by Tateuf** [comment]
same error for me, i try to use yeoman-test for my generator with mocha and exactly the same error : ( Always no solution ?

**Comment by mshima** [comment]
yeoman-test@7 is in typescript and have built-in types, maybe drop the `@types/yeoman-test` dependency?

**Comment by groovytron** [comment]
> yeoman-test@7 is in typescript and have built-in types, maybe drop the `@types/yeoman-test` dependency?

Thanks for your answer but removing `@types/yeoman-test` doesn't fix the issue. I still get the same error.

**Comment by groovytron** [comment]
I also tried to upgrade to `yeoman-test@7.3.0` but the error still persists as well.

**Comment by mshima** [comment]
yeoman-test@7 is native esm: https://github.com/yeoman/yeoman-test/releases/tag/v7.0.0

You need to convert your project to esm, commonjs won't work:
https://github.com/groovytron/generator-skjol/blob/690b27f8392c1fdd03c8fb03813f83b1bbafdaf3/package.json#L8

Or stick with yeoman-test@6

**Comment by groovytron** [comment]
@mshima thanks a lot for your help. My tests are now passing. I lost my code coverage but I'll dig into it. I'm not sure the problem comes from `yeoman-test`.

In case anybody encounters this issue, here is a diff between before and after the TypeScript migration: https://github.com/groovytron/generator-skjol/compare/1.1.1...2.0.0-rc.0

**Comment by groovytron** [comment]
I managed to fix my code coverage issue by migrating to [`c8`](https://github.com/bcoe/c8). It looks like nyc cannot generate coverage with ESM at the moment.

Here are my changes: https://github.com/groovytron/generator-skjol/commit/be4970fa9295afa80c6d2cb96c5b118bf7f3e394

Here are my findings:

- https://github.com/istanbuljs/nyc/issues/1287#issuecomment-1221560864
- https://stackoverflow.com/questions/74711290/how-to-use-esm-and-typescript-in-node-js-with-test-coverage

**Comment by mshima** [comment]
For future reference, the project don't need to be esm, tests need to be esm. Can use `mts` extension.

**Comment by ssoworld** [comment]
We should consider backward-compatibility and not have to force users to move to ECMA.  Companies using this have to **seriously consider the consequences** of not unit testing their generators and having to rely on older versions while maintaining their generators.  Sure, reverting to 6 is OK, but when one runs ```npm outdated``` or has Renovate (or equivalent) automating their updates, they have to take steps to disable this.  Let's make it simple.

**Comment by mshima** [comment]
Dependencies would be outdated since they are migrating to esm too.
A dev dependency like yeoman-test is much easier to workaround:
```js
describe(() => {
  let helpers;
  before(async() => {
    helpers = (await import('yeoman-test')).default;
  });
});
```
