### ISSUE TITLE
Breaks on node 4.7.0

### ISSUE THREAD

**Issue by selbekk** [yeoman/yeoman-test#26]
I'm having some trouble running my tests on our Jenkins instance, which is (for political reasons) running node v4.7.0. I'm running the following test:

```javascript
describe('ffe-generator', function() {
    it('creates projects with green builds', (done) => {
        helpers.run(path.join(__dirname, 'app'))
            .withOptions({
                skipInstall: false,
            })
            .withPrompts({
                name: 'test-component',
                description: 'test description',
                repourl: 'https://test.url',
            })
            // .then <-- includes the test case, but fails without it as well, so omitted
    });
});
```

I even rewrote the entire test to ES5, but that made no difference.

This happened on the newest version of both `yeoman-generator` and `yeoman-test`.

The stack trace is as follows:

```bash
Uncaught SyntaxError: Unexpected token {
      at exports.runInThisContext (vm.js:53:16)
      at require (internal/module.js:12:17)
      at Object.defineProperty.get [as ffe:app] (node_modules/yeoman-test/node_modules/yeoman-environment/lib/store.js:40:23)
      at Store.get (node_modules/yeoman-test/node_modules/yeoman-environment/lib/store.js:64:35)
      at Environment.get (node_modules/yeoman-test/node_modules/yeoman-environment/lib/environment.js:261:21)
      at Environment.create (node_modules/yeoman-test/node_modules/yeoman-environment/lib/environment.js:296:24)
      at RunContext._run (node_modules/yeoman-test/lib/run-context.js:90:29)
      at RunContext.<anonymous> (node_modules/yeoman-test/lib/run-context.js:58:10)
      at node_modules/yeoman-test/node_modules/lodash/lodash.js:5184:35
      at node_modules/yeoman-test/lib/index.js:94:5
      at next (node_modules/yeoman-test/node_modules/rimraf/rimraf.js:74:7)
      at CB (node_modules/yeoman-test/node_modules/rimraf/rimraf.js:110:9)
      at node_modules/yeoman-test/node_modules/rimraf/rimraf.js:136:14
      at FSReqWrap.oncomplete (fs.js:82:15)
```

The first relevant error, in `yeoman-environment`, references [this line in store.js](https://github.com/yeoman/environment/blob/master/lib/store.js#L40). I really can't see anything wrong with it - so I'm a bit unsure what to do here.

Thoughts?

**Comment by selbekk** [comment]
The generator itself is written in es2015 though, that might break it this way?

**Comment by selbekk** [comment]
That looked like it fixed it - sorry for the inconvenience ^^
