### ISSUE TITLE
.inTmpDir with Jest

### ISSUE THREAD

**Issue by sibelius** [yeoman/yeoman-test#27]
I'm using Jest to test [create-graphql](https://github.com/lucasbento/create-graphql)

I would like to use `inTmpDir` to move some files (fixtures) that will be read by our generator to create some GraphQL files based on mongoose schemas

That's my test: (I would like to test if generate a GraphQL ObjectType from a mongoose schema works)

```jsx
it('generate a type with Schema', async () => {
  const folder = await typeGenerator
    .inTmpDir((dir) => {
      fs.copySync(path.join(__dirname, '../fixture/Post.js'), path.join(dir, 'src/model/Post.js'));
    })
    .withArguments('Post --schema Post')
    .toPromise();

  const destinationDir = getConfigDir('type');
  const destinationTestDir = getConfigDir('type_test');

  assert.file([
    `${destinationDir}/PostType.js`, `${destinationTestDir}/PostType.spec.js`,
  ]);

  const files = {
    type: getFileContent(`${folder}/${destinationDir}/PostType.js`),
    typeTest: getFileContent(`${folder}/${destinationTestDir}/PostType.spec.js`),
  };

  expect(files).toMatchSnapshot();
});
```

That's my error:

```js
Error: ENOENT: no such file or directory, stat 'create-graphql/packages/generator/generators/type/fixture/Post.js'
at Error (native)
at Object.fs.statSync (fs.js:987:18)
at null.<anonymous> (create-graphql/node_modules/graceful-fs/polyfills.js:297:22)
at null.statSync (create-graphql/packages/generator/node_modules/graceful-fs/polyfills.js:297:22)
at Object.copySync (create-graphql/packages/generator/node_modules/fs-extra/lib/copy-sync/copy-sync.js:27:84)
at RunContext.<anonymous> (create-graphql/packages/generator/generators/type/__tests__/TypeGenerator.spec.js:79:31)
at create-graphql/packages/generator/node_modules/lodash/lodash.js:5181:46
at create-graphql/packages/generator/node_modules/yeoman-test/lib/index.js:94:5
at next (create-graphql/packages/generator/node_modules/rimraf/rimraf.js:74:7)
at CB (create-graphql/packages/generator/node_modules/rimraf/rimraf.js:110:9)
```

**Comment by SBoudrias** [comment]
Looks like `path.join(__dirname, '../fixture/Post.js')` doesn't exists.

**Comment by sibelius** [comment]
tks

it was a problem with Jest not reading the jest.json config file, this was running on transpiled files
