### ISSUE TITLE
--force option should be set by default

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman-test#4]
If it's not set, changing the content of an existing file will be very noisy and the trace is not really useful:

```
Uncaught TypeError: undefined is not a function
      at Conflicter.<anonymous> (node_modules/yeoman-generator/lib/util/conflicter.js:198:36)
      at PromptUI.onCompletion (node_modules/yeoman-test/node_modules/inquirer/lib/ui/prompt.js:57:10)
      at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1550:12)
      at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at Subject.Rx.Subject.addProperties.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5871:19)
      at Subject.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at InnerObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2966:65)
      at InnerObserver.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at InnerObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2966:65)
      at InnerObserver.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/yeoman-test/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
      at node_modules/yeoman-test/node_modules/inquirer/lib/utils/utils.js:18:13
      at f (node_modules/yeoman-test/node_modules/inquirer/node_modules/run-async/node_modules/once/once.js:17:25)
      at node_modules/yeoman-test/node_modules/inquirer/lib/ui/prompt.js:86:7
      at Immediate._onImmediate (node_modules/yeoman-test/lib/adapter.js:39:5)
```

**Comment by eddiemonge** [comment]
Its slightly better in that it at least says something isnt a function:
```
     Uncaught TypeError: this.adapter.log[result.action] is not a function
      at Conflicter.<anonymous> (node_modules/yeoman-generator/lib/util/conflicter.js:198:36)
      at PromptUI.onCompletion (node_modules/yeoman-test/node_modules/inquirer/lib/ui/prompt.js:57:10)
      at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (node_modules/rx-lite/rx.lite.js:1550:12)
      at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at Subject.Rx.Subject.addProperties.onCompleted (node_modules/rx-lite/rx.lite.js:5871:19)
      at Subject.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at InnerObserver.onCompleted (node_modules/rx-lite/rx.lite.js:2966:65)
      at InnerObserver.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at InnerObserver.onCompleted (node_modules/rx-lite/rx.lite.js:2966:65)
      at InnerObserver.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at AutoDetachObserver.tryCatcher (node_modules/rx-lite/rx.lite.js:63:31)
      at AutoDetachObserverPrototype.completed (node_modules/rx-lite/rx.lite.js:5796:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
      at node_modules/yeoman-test/node_modules/inquirer/lib/utils/utils.js:18:13
      at f (node_modules/once/once.js:17:25)
      at node_modules/yeoman-test/node_modules/inquirer/lib/ui/prompt.js:86:7
      at Immediate._onImmediate (node_modules/yeoman-test/lib/adapter.js:39:5)
```
